# check the technical writing for various characteristics
- writing/reflection.md:
    - description: Ensure that reflection.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Write a minimum number of meaningful words in the reflection
      check: CountFileWords
      options:
        count: 100
        exact: false
    - description: Confirm that the markdown file has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 4
        exact: true
    - description: Complete all TODOs, remove the TODO markers in the reflection.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true

# run the program and confirm the existence of fragments in its output
- description: 'Run the program and confirm the correct output: 4 15 23'
  check: MatchCommandFragment
  options:
    command: 'cd src; python sort.py 23 4 15'
    fragment: 4 15 23
    count: 1
    exact: true

# run the program and confirm the existence of fragments in its output
- description: 'Run the program and confirm the correct output: 23 15 4'
  check: MatchCommandFragment
  options:
    command: 'cd src; python sort.py 23 4 15'
    fragment: 23 15 4
    count: 1
    exact: true
# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits in repository
  check: CountCommits
  options:
    count: 7
